image: node:9.4.0

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - node_modules/

before_script:  
  - apt-get update -qq && apt-get install

build:
  stage: build
  script:
    - npm config ls -l
    - cp "/builds/corejsteam/3kles-corebe/.npmrc" "/root/.npmrc"
    - npm install
    - npm i -g gulp
    - npm i --savedev
    - npm run build 
    - npm publish

test:
  stage: test
  script:
    - npm run test

publish:
  stage: deploy
  script:
    - npm run build
    - npm config get
    - npm publish --verbose